// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FileMeta.proto

package org.simplefs.fs.meta.serial.proto;

public final class FileMetaProtos {
  private FileMetaProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface FileMetaOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string fileId = 1;
    /**
     * <code>required string fileId = 1;</code>
     */
    boolean hasFileId();
    /**
     * <code>required string fileId = 1;</code>
     */
    java.lang.String getFileId();
    /**
     * <code>required string fileId = 1;</code>
     */
    com.google.protobuf.ByteString
        getFileIdBytes();

    // optional string fileName = 2;
    /**
     * <code>optional string fileName = 2;</code>
     */
    boolean hasFileName();
    /**
     * <code>optional string fileName = 2;</code>
     */
    java.lang.String getFileName();
    /**
     * <code>optional string fileName = 2;</code>
     */
    com.google.protobuf.ByteString
        getFileNameBytes();

    // required int64 fileSize = 3;
    /**
     * <code>required int64 fileSize = 3;</code>
     */
    boolean hasFileSize();
    /**
     * <code>required int64 fileSize = 3;</code>
     */
    long getFileSize();

    // required int64 createTime = 4;
    /**
     * <code>required int64 createTime = 4;</code>
     */
    boolean hasCreateTime();
    /**
     * <code>required int64 createTime = 4;</code>
     */
    long getCreateTime();

    // required string innerFileId = 5;
    /**
     * <code>required string innerFileId = 5;</code>
     */
    boolean hasInnerFileId();
    /**
     * <code>required string innerFileId = 5;</code>
     */
    java.lang.String getInnerFileId();
    /**
     * <code>required string innerFileId = 5;</code>
     */
    com.google.protobuf.ByteString
        getInnerFileIdBytes();
  }
  /**
   * Protobuf type {@code FileMeta}
   */
  public static final class FileMeta extends
      com.google.protobuf.GeneratedMessage
      implements FileMetaOrBuilder {
    // Use FileMeta.newBuilder() to construct.
    private FileMeta(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private FileMeta(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final FileMeta defaultInstance;
    public static FileMeta getDefaultInstance() {
      return defaultInstance;
    }

    public FileMeta getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private FileMeta(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              fileId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              fileName_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              fileSize_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              createTime_ = input.readInt64();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              innerFileId_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.simplefs.fs.meta.serial.proto.FileMetaProtos.internal_static_FileMeta_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.simplefs.fs.meta.serial.proto.FileMetaProtos.internal_static_FileMeta_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.simplefs.fs.meta.serial.proto.FileMetaProtos.FileMeta.class, org.simplefs.fs.meta.serial.proto.FileMetaProtos.FileMeta.Builder.class);
    }

    public static com.google.protobuf.Parser<FileMeta> PARSER =
        new com.google.protobuf.AbstractParser<FileMeta>() {
      public FileMeta parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FileMeta(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<FileMeta> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string fileId = 1;
    public static final int FILEID_FIELD_NUMBER = 1;
    private java.lang.Object fileId_;
    /**
     * <code>required string fileId = 1;</code>
     */
    public boolean hasFileId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string fileId = 1;</code>
     */
    public java.lang.String getFileId() {
      java.lang.Object ref = fileId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fileId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string fileId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFileIdBytes() {
      java.lang.Object ref = fileId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string fileName = 2;
    public static final int FILENAME_FIELD_NUMBER = 2;
    private java.lang.Object fileName_;
    /**
     * <code>optional string fileName = 2;</code>
     */
    public boolean hasFileName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string fileName = 2;</code>
     */
    public java.lang.String getFileName() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fileName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string fileName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int64 fileSize = 3;
    public static final int FILESIZE_FIELD_NUMBER = 3;
    private long fileSize_;
    /**
     * <code>required int64 fileSize = 3;</code>
     */
    public boolean hasFileSize() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 fileSize = 3;</code>
     */
    public long getFileSize() {
      return fileSize_;
    }

    // required int64 createTime = 4;
    public static final int CREATETIME_FIELD_NUMBER = 4;
    private long createTime_;
    /**
     * <code>required int64 createTime = 4;</code>
     */
    public boolean hasCreateTime() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int64 createTime = 4;</code>
     */
    public long getCreateTime() {
      return createTime_;
    }

    // required string innerFileId = 5;
    public static final int INNERFILEID_FIELD_NUMBER = 5;
    private java.lang.Object innerFileId_;
    /**
     * <code>required string innerFileId = 5;</code>
     */
    public boolean hasInnerFileId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string innerFileId = 5;</code>
     */
    public java.lang.String getInnerFileId() {
      java.lang.Object ref = innerFileId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          innerFileId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string innerFileId = 5;</code>
     */
    public com.google.protobuf.ByteString
        getInnerFileIdBytes() {
      java.lang.Object ref = innerFileId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        innerFileId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      fileId_ = "";
      fileName_ = "";
      fileSize_ = 0L;
      createTime_ = 0L;
      innerFileId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasFileId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFileSize()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCreateTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasInnerFileId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getFileIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getFileNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, fileSize_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, createTime_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getInnerFileIdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getFileIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getFileNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, fileSize_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, createTime_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getInnerFileIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.simplefs.fs.meta.serial.proto.FileMetaProtos.FileMeta)) {
        return super.equals(obj);
      }
      org.simplefs.fs.meta.serial.proto.FileMetaProtos.FileMeta other = (org.simplefs.fs.meta.serial.proto.FileMetaProtos.FileMeta) obj;

      boolean result = true;
      result = result && (hasFileId() == other.hasFileId());
      if (hasFileId()) {
        result = result && getFileId()
            .equals(other.getFileId());
      }
      result = result && (hasFileName() == other.hasFileName());
      if (hasFileName()) {
        result = result && getFileName()
            .equals(other.getFileName());
      }
      result = result && (hasFileSize() == other.hasFileSize());
      if (hasFileSize()) {
        result = result && (getFileSize()
            == other.getFileSize());
      }
      result = result && (hasCreateTime() == other.hasCreateTime());
      if (hasCreateTime()) {
        result = result && (getCreateTime()
            == other.getCreateTime());
      }
      result = result && (hasInnerFileId() == other.hasInnerFileId());
      if (hasInnerFileId()) {
        result = result && getInnerFileId()
            .equals(other.getInnerFileId());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasFileId()) {
        hash = (37 * hash) + FILEID_FIELD_NUMBER;
        hash = (53 * hash) + getFileId().hashCode();
      }
      if (hasFileName()) {
        hash = (37 * hash) + FILENAME_FIELD_NUMBER;
        hash = (53 * hash) + getFileName().hashCode();
      }
      if (hasFileSize()) {
        hash = (37 * hash) + FILESIZE_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(getFileSize());
      }
      if (hasCreateTime()) {
        hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(getCreateTime());
      }
      if (hasInnerFileId()) {
        hash = (37 * hash) + INNERFILEID_FIELD_NUMBER;
        hash = (53 * hash) + getInnerFileId().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.simplefs.fs.meta.serial.proto.FileMetaProtos.FileMeta parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.simplefs.fs.meta.serial.proto.FileMetaProtos.FileMeta parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.simplefs.fs.meta.serial.proto.FileMetaProtos.FileMeta parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.simplefs.fs.meta.serial.proto.FileMetaProtos.FileMeta parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.simplefs.fs.meta.serial.proto.FileMetaProtos.FileMeta parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.simplefs.fs.meta.serial.proto.FileMetaProtos.FileMeta parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.simplefs.fs.meta.serial.proto.FileMetaProtos.FileMeta parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.simplefs.fs.meta.serial.proto.FileMetaProtos.FileMeta parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.simplefs.fs.meta.serial.proto.FileMetaProtos.FileMeta parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.simplefs.fs.meta.serial.proto.FileMetaProtos.FileMeta parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.simplefs.fs.meta.serial.proto.FileMetaProtos.FileMeta prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FileMeta}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.simplefs.fs.meta.serial.proto.FileMetaProtos.FileMetaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.simplefs.fs.meta.serial.proto.FileMetaProtos.internal_static_FileMeta_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.simplefs.fs.meta.serial.proto.FileMetaProtos.internal_static_FileMeta_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.simplefs.fs.meta.serial.proto.FileMetaProtos.FileMeta.class, org.simplefs.fs.meta.serial.proto.FileMetaProtos.FileMeta.Builder.class);
      }

      // Construct using org.simplefs.fs.meta.serial.proto.FileMetaProtos.FileMeta.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        fileId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        fileName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        fileSize_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        createTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        innerFileId_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.simplefs.fs.meta.serial.proto.FileMetaProtos.internal_static_FileMeta_descriptor;
      }

      public org.simplefs.fs.meta.serial.proto.FileMetaProtos.FileMeta getDefaultInstanceForType() {
        return org.simplefs.fs.meta.serial.proto.FileMetaProtos.FileMeta.getDefaultInstance();
      }

      public org.simplefs.fs.meta.serial.proto.FileMetaProtos.FileMeta build() {
        org.simplefs.fs.meta.serial.proto.FileMetaProtos.FileMeta result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.simplefs.fs.meta.serial.proto.FileMetaProtos.FileMeta buildPartial() {
        org.simplefs.fs.meta.serial.proto.FileMetaProtos.FileMeta result = new org.simplefs.fs.meta.serial.proto.FileMetaProtos.FileMeta(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.fileId_ = fileId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.fileName_ = fileName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.fileSize_ = fileSize_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.createTime_ = createTime_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.innerFileId_ = innerFileId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.simplefs.fs.meta.serial.proto.FileMetaProtos.FileMeta) {
          return mergeFrom((org.simplefs.fs.meta.serial.proto.FileMetaProtos.FileMeta)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.simplefs.fs.meta.serial.proto.FileMetaProtos.FileMeta other) {
        if (other == org.simplefs.fs.meta.serial.proto.FileMetaProtos.FileMeta.getDefaultInstance()) return this;
        if (other.hasFileId()) {
          bitField0_ |= 0x00000001;
          fileId_ = other.fileId_;
          onChanged();
        }
        if (other.hasFileName()) {
          bitField0_ |= 0x00000002;
          fileName_ = other.fileName_;
          onChanged();
        }
        if (other.hasFileSize()) {
          setFileSize(other.getFileSize());
        }
        if (other.hasCreateTime()) {
          setCreateTime(other.getCreateTime());
        }
        if (other.hasInnerFileId()) {
          bitField0_ |= 0x00000010;
          innerFileId_ = other.innerFileId_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFileId()) {
          
          return false;
        }
        if (!hasFileSize()) {
          
          return false;
        }
        if (!hasCreateTime()) {
          
          return false;
        }
        if (!hasInnerFileId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.simplefs.fs.meta.serial.proto.FileMetaProtos.FileMeta parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.simplefs.fs.meta.serial.proto.FileMetaProtos.FileMeta) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string fileId = 1;
      private java.lang.Object fileId_ = "";
      /**
       * <code>required string fileId = 1;</code>
       */
      public boolean hasFileId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string fileId = 1;</code>
       */
      public java.lang.String getFileId() {
        java.lang.Object ref = fileId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          fileId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string fileId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFileIdBytes() {
        java.lang.Object ref = fileId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string fileId = 1;</code>
       */
      public Builder setFileId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        fileId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string fileId = 1;</code>
       */
      public Builder clearFileId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fileId_ = getDefaultInstance().getFileId();
        onChanged();
        return this;
      }
      /**
       * <code>required string fileId = 1;</code>
       */
      public Builder setFileIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        fileId_ = value;
        onChanged();
        return this;
      }

      // optional string fileName = 2;
      private java.lang.Object fileName_ = "";
      /**
       * <code>optional string fileName = 2;</code>
       */
      public boolean hasFileName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string fileName = 2;</code>
       */
      public java.lang.String getFileName() {
        java.lang.Object ref = fileName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          fileName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string fileName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFileNameBytes() {
        java.lang.Object ref = fileName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string fileName = 2;</code>
       */
      public Builder setFileName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        fileName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string fileName = 2;</code>
       */
      public Builder clearFileName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        fileName_ = getDefaultInstance().getFileName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string fileName = 2;</code>
       */
      public Builder setFileNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        fileName_ = value;
        onChanged();
        return this;
      }

      // required int64 fileSize = 3;
      private long fileSize_ ;
      /**
       * <code>required int64 fileSize = 3;</code>
       */
      public boolean hasFileSize() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 fileSize = 3;</code>
       */
      public long getFileSize() {
        return fileSize_;
      }
      /**
       * <code>required int64 fileSize = 3;</code>
       */
      public Builder setFileSize(long value) {
        bitField0_ |= 0x00000004;
        fileSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 fileSize = 3;</code>
       */
      public Builder clearFileSize() {
        bitField0_ = (bitField0_ & ~0x00000004);
        fileSize_ = 0L;
        onChanged();
        return this;
      }

      // required int64 createTime = 4;
      private long createTime_ ;
      /**
       * <code>required int64 createTime = 4;</code>
       */
      public boolean hasCreateTime() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int64 createTime = 4;</code>
       */
      public long getCreateTime() {
        return createTime_;
      }
      /**
       * <code>required int64 createTime = 4;</code>
       */
      public Builder setCreateTime(long value) {
        bitField0_ |= 0x00000008;
        createTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 createTime = 4;</code>
       */
      public Builder clearCreateTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        createTime_ = 0L;
        onChanged();
        return this;
      }

      // required string innerFileId = 5;
      private java.lang.Object innerFileId_ = "";
      /**
       * <code>required string innerFileId = 5;</code>
       */
      public boolean hasInnerFileId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string innerFileId = 5;</code>
       */
      public java.lang.String getInnerFileId() {
        java.lang.Object ref = innerFileId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          innerFileId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string innerFileId = 5;</code>
       */
      public com.google.protobuf.ByteString
          getInnerFileIdBytes() {
        java.lang.Object ref = innerFileId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          innerFileId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string innerFileId = 5;</code>
       */
      public Builder setInnerFileId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        innerFileId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string innerFileId = 5;</code>
       */
      public Builder clearInnerFileId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        innerFileId_ = getDefaultInstance().getInnerFileId();
        onChanged();
        return this;
      }
      /**
       * <code>required string innerFileId = 5;</code>
       */
      public Builder setInnerFileIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        innerFileId_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:FileMeta)
    }

    static {
      defaultInstance = new FileMeta(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:FileMeta)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_FileMeta_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FileMeta_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016FileMeta.proto\"g\n\010FileMeta\022\016\n\006fileId\030\001" +
      " \002(\t\022\020\n\010fileName\030\002 \001(\t\022\020\n\010fileSize\030\003 \002(\003" +
      "\022\022\n\ncreateTime\030\004 \002(\003\022\023\n\013innerFileId\030\005 \002(" +
      "\tB;\n!org.simplefs.fs.meta.serial.protoB\016" +
      "FileMetaProtosH\001\210\001\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_FileMeta_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_FileMeta_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_FileMeta_descriptor,
              new java.lang.String[] { "FileId", "FileName", "FileSize", "CreateTime", "InnerFileId", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
